apiVersion: v1
kind: Service
metadata:
  name: coll-4ce43fbcd5ff431293e87d1ac2dc2d08-srv
spec:
  selector:
    app: coll-4ce43fbcd5ff431293e87d1ac2dc2d08
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP